package com.javachinna.model;

public enum Citations {

    Never_apologize_being_a_powerful_woman,
    Each_time_a_woman_stands_up_for_herself_she_stands_up_for_all_women___Maya_Angelou,
    A_woman_is_the_full_circle__Within_her_is_the_power_to_create__nurture_and_transform____Diane_Mariechild,
    A_strong_woman_stands_up_for_herself__A_stronger_woman_stands_up_for_everybody_else,
    And_one_day_she_discovered_that_she_was_fierce__and_strong__and_full_of_fire__and_that_not_even_she_could_hold_herself_back_because_her_passion_burned_brighter_than_her_fears___Mark_Anthony,
    She_was_a_wild_one__always_somping_on_eggshells_that_everyone_else_tip_toed_on__Kaitlin_Foster,
    She_was_powerful_not_because_she_was_not_scared_but_because_she_went_on_so_strongly__despite_the_fear__Atticus,
    One_of_the_most_courageous_things_you_can_do_is_identify_yourself__know_who_you_are__what_you_believe_in_and_where_you_want_to_go__Sheila_Murray_Bethel,
    Avoiding_danger_is_no_safer_in_the_long_run_than_outright_exposure__The_fearful_are_caught_as_often_as_the_bold__Helen_Keller


    }